# Generated by Django 5.2 on 2025-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelroom",
            name="description",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="hotelroom",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
