# Generated by Django 5.2 on 2025-05-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0002_alter_hotelroom_description_alter_hotelroom_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelroom",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
