# Generated by Django 5.2.1 on 2025-05-29 22:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_alter_hotelroom_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Booking",
        ),
    ]
