# Generated by Django 5.2.1 on 2025-05-29 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotel", "0004_delete_booking"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_booking", models.DateField()),
                ("end_booking", models.DateField()),
                ("date_create", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel.hotelroom",
                    ),
                ),
            ],
        ),
    ]
